// Minimal agent host: exposes a simple HTTP API that returns a mock plan
const http = require('http')

const PORT = 3001

const server = http.createServer(async (req, res) => {
  if (req.method === 'POST' && req.url === '/plan') {
    let body = ''
    for await (const chunk of req) body += chunk
    try {
      const data = JSON.parse(body || '{}')

      // Simple RAS-like salience detection (keyword and length heuristics)
      const ctx = (data.context || '')
      const keywords = ['TODO','fix','bug','refactor','optimi','test','error','panic']
      let kwCount = 0
      for (const k of keywords) if (ctx.toLowerCase().includes(k.toLowerCase())) kwCount++
      const lengthScore = Math.min(1, ctx.length / 2000)
      const salience = Math.min(1, kwCount * 0.25 + lengthScore * 0.5)

      // Build a lightweight suggestion: header + brief checklist + context snippet
      const snippet = ctx.split('\n').slice(0, 40).join('\n')
      const suggestion = `/* Agent Suggestion: header + quick checklist */\n// - Add file header\n// - Run tests\n// - Consider small refactor suggestions below\n\n${snippet}\n\n/* End suggestion */`

      const plan = {
        summary: 'Mock plan generated by agent-host with salience filter',
        analysisTokens: ctx.length,
        salience: Number(salience.toFixed(3)),
        suggestion,
        // Structured edits: simple insertion of suggestion at file top (startLine 0)
        edits: [
          {
            startLine: 0,
            endLine: 0,
            replacement: suggestion
          }
        ],
        steps: [
          'Run static analysis',
          'Propose small refactor',
          'Open PR with tests'
        ]
      }
      res.writeHead(200, { 'Content-Type': 'application/json' })
      res.end(JSON.stringify(plan))
    } catch (err) {
      res.writeHead(400)
      res.end('bad request')
    }
    return
  }

  res.writeHead(404)
  res.end('not found')
})

server.listen(PORT, '127.0.0.1', () => {
  console.log('Agent host listening on http://127.0.0.1:' + PORT)
})
